import Phaser from 'phaser';

interface IWordChain {
    words: string[];
    bonusWords: string[];
    land: string;
    level: number;
}

const WORD_CHAINS: IWordChain[] = [
    // Chain 1: Classic associations
    {
        words: ['CAR', 'DOOR', 'STOP', 'SIGN', 'UP', 'START', 'BUTTON', 'NOSE', 'RING', 'BELL', 'TOWER', 'CLOCK'],
        bonusWords: ['TOWER', 'WORK', 'OUT'], // Bonus words for streak
        land: 'Corinthia',
        level: 1
    },
    // Chain 2: Nature theme
    {
        words: ['SUN', 'FLOWER', 'POT', 'LUCK', 'CHARM', 'SCHOOL', 'BUS', 'STOP', 'WATCH', 'DOG', 'HOUSE', 'BOAT'],
        bonusWords: ['RACE', 'CAR', 'POOL'],
        land: 'Corinthia',
        level: 2
    },
    // Chain 3: Technology theme
    {
        words: ['PHONE', 'CALL', 'BACK', 'PACK', 'RAT', 'RACE', 'TRACK', 'FIELD', 'GOAL', 'POST', 'OFFICE', 'SPACE'],
        bonusWords: ['BAR', 'CODE', 'WORD'],
        land: 'Corinthia',
        level: 3
    }
];

export default class GameplayScene extends Phaser.Scene {
    private currentChainIndex: number = 0;
    private currentWordIndex: number = 0;
    private score: number = 0;
    private streak: number = 0;
    private maxStreak: number = 0;
    private lives: number = 3;
    private wrongAttempts: number = 0;
    private perfectWords: number = 0;
    private combo: number = 0;
    private maxCombo: number = 100;
    private startTime: number | null = null;
    private isPlaying: boolean = false;
    private bonusWordsUnlocked: number = 0;

    private wordGridContainer!: Phaser.GameObjects.DOMElement;
    private wordInput!: Phaser.GameObjects.DOMElement;
    private comboText!: Phaser.GameObjects.DOMElement;
    private progressBar!: Phaser.GameObjects.DOMElement;
    private progressText!: Phaser.GameObjects.DOMElement;
    private ruutCharacter!: Phaser.GameObjects.DOMElement;
    private overlay!: Phaser.GameObjects.DOMElement;
    private feedbackFloat!: Phaser.GameObjects.DOMElement;
    private settingsBtn!: Phaser.GameObjects.DOMElement;
    private levelIndicator!: Phaser.GameObjects.DOMElement;
    private currencyDisplay!: Phaser.GameObjects.DOMElement;
    private streakDisplayValue!: Phaser.GameObjects.DOMElement;
    private scoreDisplayValue!: Phaser.GameObjects.DOMElement;
    private livesDisplay!: Phaser.GameObjects.DOMElement;
    private hintDisplay!: Phaser.GameObjects.DOMElement;
    private hintBtn!: Phaser.GameObjects.DOMElement;
    private shuffleBtn!: Phaser.GameObjects.DOMElement;
    private bonusDisplay!: Phaser.GameObjects.DOMElement;
    private maxComboStat!: Phaser.GameObjects.DOMElement;
    private accuracyStat!: Phaser.GameObjects.DOMElement;

    private ruutStates = {
        wave: '&#128075;',
        idle: '&#128578;',
        happy: '&#127881;',
        hurray: '&#129395;',
        sad: '&#128546;',
        dance: '&#128131;'
    };

    constructor() {
        super('GameplayScene');
    }

    private get chain(): IWordChain {
        return WORD_CHAINS[this.currentChainIndex];
    }

    private get allWords(): string[] {
        const base = [...this.chain.words];
        for (let i = 0; i < this.bonusWordsUnlocked; i++) {
            if (this.chain.bonusWords[i]) {
                base.push(this.chain.bonusWords[i]);
            }
        }
        return base;
    }

    create() {


        this.add.dom(this.scale.width / 2, 0).createFromHTML(`
            <div class="game-container w-[390px] h-[844px] bg-gradient-to-b from-[#0e0e12] via-[#1a1a2e] to-[#0e0e12] relative overflow-hidden rounded-2xl shadow-2xl">
                <!-- Top Bar -->
                <div class="top-bar absolute top-0 left-0 right-0 h-[60px] p-[15px] px-[20px] flex justify-between items-center z-10">
                    <button class="settings-btn">&#9881;</button>
                    <div class="level-indicator">Lv: 1</div>
                    <div class="lives-display" id="livesDisplay">
                        <span class="life-heart">❤️</span>
                        <span class="life-heart">❤️</span>
                        <span class="life-heart">❤️</span>
                    </div>
                    <div class="streak-display">
                        <span>🔥</span>
                        <span id="streakValue">0</span>
                    </div>
                    <div class="currency-display">
                        <span>💰</span>
                        <span id="scoreValue">1,250</span>
                    </div>
                </div>

                <!-- Word Grid -->
                <div class="word-grid-container" id="wordGrid">
                    <!-- Words will be generated by JS -->
                </div>

                <!-- Combo Display -->
                <div class="combo-display">
                    <span class="combo-text" id="comboText">COMBO X 1</span>
                </div>

                <!-- Hint Display -->
                <div class="hint-display" id="hintDisplay">Type the associated word...</div>

                <!-- Input Area -->
                <div class="input-area">
                    <input type="text" class="word-input" id="wordInput" placeholder="TYPE HERE" autocomplete="off" autocapitalize="characters">
                    <button class="submit-btn" id="submitBtn">✔</button>
                </div>

                <!-- Progress -->
                <div class="progress-container">
                    <div class="progress-bar" id="progressBar"></div>
                </div>
                <div class="progress-text" id="progressText">0 / 11 Words</div>

                <!-- Bottom Bar -->
                <div class="bottom-bar">
                    <span class="ruut-label">RUUT</span>
                    <div class="ruut-container" id="ruutCharacter">
                        &#128075;
                    </div>

                    <div class="action-buttons">
                        <button class="action-btn hint-btn" title="Hint">&#128161;</button>
                        <button class="action-btn" title="Shuffle">&#128260;</button>
                    </div>

                    <div class="bonus-display">BONUS Words: 0/5</div>
                </div>

                <!-- Level Complete Overlay -->
                <div class="overlay" id="overlay">
                    <div class="overlay-title">LEVEL COMPLETE!</div>
                    <div class="overlay-stats">
                        <div class="stat-row">
                            <span>Words Completed:</span>
                            <span class="stat-value">11/11</span>
                        </div>
                        <div class="stat-row">
                            <span>Max Combo:</span>
                            <span class="stat-value" id="maxComboStat">0</span>
                        </div>
                        <div class="stat-row">
                            <span>Accuracy:</span>
                            <span class="stat-value" id="accuracyStat">100%</span>
                        </div>
                    </div>
                    <button class="play-again-btn" id="playAgainBtn">PLAY AGAIN</button>
                </div>

                <!-- Floating Feedback -->
                <div class="feedback-float" id="feedbackFloat"></div>
            </div>
        `);

        this.wordGridContainer = this.add.dom(0,0);
        this.wordInput = this.add.dom(0,0);
        this.comboText = this.add.dom(0,0);
        this.progressBar = this.add.dom(0,0);
        this.progressText = this.add.dom(0,0);
        this.ruutCharacter = this.add.dom(0,0);
        this.overlay = this.add.dom(0,0);
        this.feedbackFloat = this.add.dom(0,0);

        this.time.delayedCall(100, () => {

            const wordGridEl = document.getElementById('wordGrid');
            if (wordGridEl) this.wordGridContainer.setElement(wordGridEl);

        this.time.delayedCall(100, () => {
            this.wordGridContainer.setElement(document.getElementById('wordGrid'));
            this.wordInput.setElement(document.getElementById('wordInput'));
            this.comboText.setElement(document.getElementById('comboText'));
            this.progressBar.setElement(document.getElementById('progressBar'));
            this.progressText.setElement(document.getElementById('progressText'));
            this.ruutCharacter.setElement(document.getElementById('ruutCharacter'));
            this.overlay.setElement(document.getElementById('overlay'));
            this.feedbackFloat.setElement(document.getElementById('feedbackFloat'));
            // New elements
            this.settingsBtn.setElement(document.querySelector('.settings-btn')!);
            this.levelIndicator.setElement(document.querySelector('.level-indicator')!);
            this.livesDisplay.setElement(document.getElementById('livesDisplay')!);
            this.streakDisplayValue.setElement(document.getElementById('streakValue')!);
            this.scoreDisplayValue.setElement(document.getElementById('scoreValue')!);
            this.currencyDisplay.setElement(document.querySelector('.currency-display')!);
            this.hintDisplay.setElement(document.getElementById('hintDisplay')!);
            this.hintBtn.setElement(document.querySelector('.hint-btn')!);
            this.shuffleBtn.setElement(document.querySelector('.action-buttons button:nth-child(2)')!);
            this.bonusDisplay.setElement(document.querySelector('.bonus-display')!);
            this.maxComboStat.setElement(document.getElementById('maxComboStat')!);
            this.accuracyStat.setElement(document.getElementById('accuracyStat')!);

            const submitBtn = document.getElementById('submitBtn');
            const playAgainBtn = document.getElementById('playAgainBtn');
            const ruutCharacterEl = document.getElementById('ruutCharacter');

            if (submitBtn) {
                submitBtn.addEventListener('click', () => this.checkAnswer());
            }

            if (this.wordInput.node) {
              (this.wordInput.node as HTMLInputElement).addEventListener('keypress', (e) => {
                  if (e.key === 'Enter') {
                      this.checkAnswer();
                  }
              });
            }

            if (playAgainBtn) {
                playAgainBtn.addEventListener('click', () => this.resetGame());
            }

            if (ruutCharacterEl) {
              ruutCharacterEl.addEventListener('click', () => {
                this.setRuutState('happy');
                setTimeout(() => this.setRuutState('idle'), 500);
              });
            }

            this._initSceneUIAndInput();
        });
    }
    private _initSceneUIAndInput() {
        // Initial Ruut wave animation
        setTimeout(() => {
            this.setRuutState('wave');
            setTimeout(() => this.setRuutState('idle'), 1000);
        }, 500);
    }

    private start() {
        this.isPlaying = true;

        this.renderWordGrid();
        this.updateProgress();
        this.updateCombo();
        this.updateScore(this.score);
        this.updateStreak(this.streak);
        this.updateLives(this.lives);

        if (this.wordInput.node) {
            (this.wordInput.node as HTMLInputElement).focus();
        }

        // Show initial hint
        const firstWord = this.chain.words[0];
        this.updateHint(`Previous word: START | Think: What word goes with "${firstWord[0]}___"?`);
    }

    private renderWordGrid() {
        const wordGrid = this.wordGridContainer.node as HTMLElement;
        if (!wordGrid) return;

        wordGrid.innerHTML = '';
        const words = this.allWords;
        const currentIndex = this.currentWordIndex;

        for (let i = 0; i < words.length; i++) {
            const word = words[i];
            const isCompleted = i < currentIndex;
            const isCurrent = i === currentIndex;
            const isLocked = i > currentIndex;
            const isBonus = i >= this.chain.words.length; // Check against core words length

            let classes = 'word-rung';
            if (isCompleted) classes += ' completed';
            if (isCurrent) classes += ' current';
            if (isLocked) classes += ' locked';
            if (isBonus) classes += ' bonus';

            let wordDisplay = '';
            if (isCompleted) {
                wordDisplay = `<span class="word-display revealed">${word}</span>`;
            } else if (isCurrent) {
                wordDisplay = `<span class="word-display"><span class="first-letter">${word[0]}</span>${'_'.repeat(word.length - 1)}</span>`;
            } else {
                wordDisplay = `<span class="word-display hidden">${'?'.repeat(word.length)}</span>`;
            }

            const rung = document.createElement('div');
            rung.className = classes;
            rung.id = `rung-${i}`;
            rung.setAttribute('data-index', i.toString());
            rung.innerHTML = `
                <span class="rung-number">${i + 1}</span>
                ${wordDisplay}
            `;

            wordGrid.appendChild(rung);
        }

        this.updateRuutPosition();
    }

    private updateRuutPosition() {
        // Placeholder for Ruut position update
        // The actual implementation will be added later when we handle UI positioning more precisely.
    }

    private updateProgress() {
        const progressBar = this.progressBar.node as HTMLElement;
        const progressText = this.progressText.node as HTMLElement;

        if (!progressBar || !progressText) return;

        const progress = (this.currentWordIndex / this.allWords.length) * 100;
        progressBar.style.width = `${progress}%`;
        progressText.textContent = `${this.currentWordIndex} / ${this.allWords.length} Words`;
    }

    private updateCombo() {
        const comboText = this.comboText.node as HTMLElement;
        if (!comboText) return;

        comboText.textContent = `COMBO X ${this.combo}`;
        comboText.classList.remove('pop');
        void comboText.offsetWidth;
        comboText.classList.add('pop');
    }

    private updateScore(newScore: number) {
        if (this.scoreDisplayValue.node) {
            (this.scoreDisplayValue.node as HTMLElement).textContent = newScore.toLocaleString();
        }
    }

    private updateStreak(streak: number) {
        if (this.streakDisplayValue.node) {
            (this.streakDisplayValue.node as HTMLElement).textContent = streak.toString();
            // TODO: Add animation for streak display (flame flicker from MVP)
        }
    }

    private updateLives(lives: number) {
        if (this.livesDisplay.node) {
            const hearts = this.livesDisplay.node.querySelectorAll('.life-heart');
            hearts.forEach((heart, i) => {
                if (i >= lives) {
                    heart.classList.add('lost');
                } else {
                    heart.classList.remove('lost');
                }
            });
        }
    }

    private updateHint(text: string) {
        if (this.hintDisplay.node) {
            (this.hintDisplay.node as HTMLElement).textContent = text;
        }
    }

    private setRuutState(state: keyof typeof this.ruutStates) {
        const ruutCharacter = this.ruutCharacter.node as HTMLElement;
        if (!ruutCharacter) return;

        ruutCharacter.innerHTML = this.ruutStates[state] || this.ruutStates.idle;

        ruutCharacter.classList.remove('happy', 'sad');
        if (state === 'happy' || state === 'hurray' || state === 'dance') {
            ruutCharacter.classList.add('happy');
        } else if (state === 'sad') {
            ruutCharacter.classList.add('sad');
        }
    }

    private showFeedback(text: string, isCorrect: boolean) {
        const feedbackFloat = this.feedbackFloat.node as HTMLElement;
        if (!feedbackFloat) return;

        feedbackFloat.textContent = text;
        feedbackFloat.className = 'feedback-float show ' + (isCorrect ? 'correct' : 'wrong');
        feedbackFloat.style.left = '50%';
        feedbackFloat.style.top = '480px';
        feedbackFloat.style.transform = 'translateX(-50%)';

        setTimeout(() => {
            feedbackFloat.classList.remove('show');
        }, 500);
    }

    private levenshteinDistance(a: string, b: string): number {
        if (a.length === 0) return b.length;
        if (b.length === 0) return a.length;

        const matrix: number[][] = [];

        for (let i = 0; i <= b.length; i++) {
            matrix[i] = [i];
        }

        for (let j = 0; j <= a.length; j++) {
            matrix[0][j] = j;
        }

        for (let i = 1; i <= b.length; i++) {
            for (let j = 1; j <= a.length; j++) {
                if (b.charAt(i - 1) === a.charAt(j - 1)) {
                    matrix[i][j] = matrix[i - 1][j - 1];
                } else {
                    matrix[i][j] = Math.min(
                        matrix[i - 1][j - 1] + 1,
                        matrix[i][j - 1] + 1,
                        matrix[i - 1][j] + 1
                    );
                }
            }
        }

        return matrix[b.length][a.length];
    }

    private _checkWord(submitted: string, target: string): boolean {
        if (submitted === target) return true;

        if (target.length >= 4) {
            const distance = this.levenshteinDistance(submitted, target);
            if (distance === 1) {
                // TODO: Show typo forgiveness feedback (e.g., Renderer.updateHint)
                // this.updateHint(`Close enough! (Typo forgiven: ${target})`);
                return true;
            }
        }
        return false;
    }

    private handleCorrectAnswer() {
        this.totalAttempts++;
        this.correctAttempts++;
        
        // Update state
        this.currentWordIndex++;
        this.streak++; // Use this.streak from MVP
        this.maxStreak = Math.max(this.maxStreak, this.streak);
        this.perfectWords++;
        this.wrongAttempts = 0; // Reset on correct answer

        // Calculate score
        const basePoints = 100;
        const streakMultiplier = 1 + (this.streak * 0.1);
        const points = Math.round(basePoints * streakMultiplier);
        this.score += points;

        // Update combo
        this.combo = Math.min(this.maxCombo, this.combo + 20);

        // Check for bonus word unlock
        if (this.streak >= 3 && this.bonusWordsUnlocked < 3) {
            if (this.combo >= 80) { // MVP uses combo >= 80 for bonus unlock
                this.bonusWordsUnlocked++;
                this.updateHint(`BONUS WORD UNLOCKED! Streak x${this.streak}`);
            }
        }

        // Visual effects
        const wordInput = this.wordInput.node as HTMLInputElement;
        wordInput.classList.add('correct');
        setTimeout(() => wordInput.classList.remove('correct'), 200);

        const currentRung = document.getElementById(`rung-${this.currentWordIndex - 1}`); // Old current rung
        if (currentRung) {
            currentRung.classList.add('correct-flash');
        }
        this.setRuutState('happy'); // Using happy for general correct, MVP uses ruutJump which we don't have yet
        setTimeout(() => this.setRuutState('idle'), 800);

        this.showFeedback('+' + points, true); // Show actual points gained

        // Update displays
        this.renderWordGrid(); // Rerender ladder for new current word
        this.updateProgress();
        this.updateScore(this.score);
        this.updateStreak(this.streak);
        this.updateCombo();

        // Check for level complete
        if (this.currentWordIndex >= this.allWords.length) {
            this.levelComplete();
        } else {
            // Update hint for next word
            const nextWord = this.allWords[this.currentWordIndex];
            const prevWord = this.allWords[this.currentWordIndex - 1];
            this.updateHint(`Previous: ${prevWord} | Next starts with: ${nextWord[0]}`);
        }
    }

    private handleWrongAnswer() {
        this.totalAttempts++;

        // Update state
        this.streak = 0; // Reset streak on wrong answer
        this.wrongAttempts++;
        this.combo = Math.max(0, this.combo - 30); // Penalty to combo

        // Penalty points
        this.score = Math.max(0, this.score - 50);

        // Check for life loss (3 wrong = 1 life)
        if (this.wrongAttempts >= 3) {
            this.lives--;
            this.wrongAttempts = 0; // Reset wrong attempts after losing a life
            this.updateLives(this.lives);

            if (this.lives <= 0) {
                this.gameOver(); // Placeholder for game over logic
                return;
            }
        }

        // Visual effects
        const wordInput = this.wordInput.node as HTMLInputElement;
        wordInput.classList.add('shake', 'wrong');
        setTimeout(() => {
            wordInput.classList.remove('shake', 'wrong');
        }, 300);

        this.showFeedback('WRONG!', false);
        this.setRuutState('sad');
        setTimeout(() => this.setRuutState('idle'), 800);
        
        // Update displays
        this.updateScore(this.score);
        this.updateStreak(this.streak);
        this.updateCombo();
        this.updateLives(this.lives); // Update lives display after potential loss

        // Helpful hint
        const targetWord = this.allWords[this.currentWordIndex];
        const prevWord = this.currentWordIndex > 0
            ? this.allWords[this.currentWordIndex - 1]
            : 'START';
        this.updateHint(`Not quite! Think: "${prevWord}" + "${targetWord[0]}___" (${this.wrongAttempts}/3 attempts)`);
    }

    private checkAnswer() {
        const wordInput = this.wordInput.node as HTMLInputElement;
        const userAnswer = wordInput.value.trim().toUpperCase();
        const correctAnswer = this.allWords[this.currentWordIndex];

        if (!userAnswer) return;

        const isCorrect = this._checkWord(userAnswer, correctAnswer);

        if (isCorrect) {
            this.handleCorrectAnswer();
        } else {
            this.handleWrongAnswer();
        }

        wordInput.value = ''; // Clear input
        wordInput.focus();
    }

    private levelComplete() {
        this.setRuutState('dance');

        const maxComboStat = document.getElementById('maxComboStat');
        const accuracyStat = document.getElementById('accuracyStat');
        const overlay = this.overlay.node as HTMLElement;

        if (maxComboStat) {
          maxComboStat.textContent = this.maxCombo.toString();
        }
        if (accuracyStat) {
          const accuracy = Math.round((this.correctAttempts / this.totalAttempts) * 100);
          accuracyStat.textContent = accuracy + '%';
        }


        setTimeout(() => {
            if(overlay) {
              overlay.classList.add('show');
            }
        }, 500);
    }

    private gameOver() {
        // Placeholder for game over logic
        console.log("GAME OVER!");
        // For MVP, just restart immediately for now.
        setTimeout(() => {
            this.lives = 3; // Reset lives for restart
            this.start();
        }, 2000);
    }

    private resetGame() {
        this.currentWordIndex = 0;
        this.score = 0;
        this.streak = 0;
        this.maxStreak = 0;
        this.lives = 3;
        this.wrongAttempts = 0;
        this.perfectWords = 0;
        this.combo = 0;
        this.maxCombo = 100;
        this.startTime = Date.now();
        this.isPlaying = true;
        this.bonusWordsUnlocked = 0;
        this.totalAttempts = 0;
        this.correctAttempts = 0;

        const overlay = this.overlay.node as HTMLElement;
        if(overlay) {
          overlay.classList.remove('show');
        }

        const wordInput = this.wordInput.node as HTMLInputElement;
        wordInput.value = '';

        this.start();
    }
}